improve single option for tui to parse alternative configuration file

diff --git a/onionjuggler-tui b/onionjuggler-tui
--- a/onionjuggler-tui
+++ b/onionjuggler-tui
@@ -10,13 +10,28 @@
 ## Lines that begin with "## " try to explain what's going on. Lines
 ## that begin with just "#" are disabled commands.
 
+## display error message with instructions to use the script correctly.
+error_msg(){ printf %s"\033[0;31mERROR: ${1}\033[0m\n"; exit 1; }
+
 ###################
 #### VARIABLES ####
 
 ## cli has to see the config argument, so export it
-case "${1}" in
-  -C|--config|-C=*|--config=*) onionjuggler_conf="${1#*=}"; export onionjuggler_conf;;
-esac
+assign_value(){ case "${2}" in --*) value="${2#--}";; -*) value="${2#-}";; *) value="${2}";; esac; eval "${1}"="${value}"; }
+get_arg(){ case "${3}" in ""|-*) error_msg "Option '${2}' requires an argument.";; esac; assign_value "${1}" "${3}"; }
+while :; do
+  case "${1}" in
+    -*=*) opt="${1%=*}"; arg="${1#*=}"; shift_n=1;;
+    -*) opt="${1}"; arg="${2}"; shift_n=2;;
+  esac
+  case "${1}" in
+    -C|--config|-C=*|--config=*) get_arg onionjuggler_conf "${opt}" "${arg}"; export onionjuggler_conf;;
+    "") break;;
+    *) error_msg "Invalid option: ${opt}";;
+  esac
+  shift "${shift_n}"
+done
+
 [ -r "${onionjuggler_conf:="/etc/onionjuggler.conf"}" ] && . "${onionjuggler_conf}"
 ## if any of the configurations are empty, use default ones
 
@@ -54,9 +69,6 @@ i=0
 
 ###########################
 ######## FUNCTIONS ########
-
-## display error message with instructions to use the script correctly.
-error_msg(){ printf %s"\033[0;31mERROR: ${1}\033[0m\n"; exit 1; }
 
 if ! command -v onionjuggler-cli >/dev/null && [ ! -f onionjuggler-cli ]; then
   error_msg "onionjuggler-cli not found on PATH!"
@@ -146,7 +158,7 @@ if [ -z "$("${exec_cmd_alt_user}" -u "${tor_user}" ls "${tor_data_dir_services}"
   3>&1 1>&2 2>&3)"
 else
   choice_main="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
-  "${ok_flag}" "Select" "${no_cancel_flag}" --menu "${menu}" "$((20+whiptail_height))" 80 12 \
+  "${ok_flag}" "Select" "${no_cancel_flag}" --menu "${menu}" "$((19+whiptail_height))" 80 11 \
   "QUIT" "Exit menu and clear the screen" \
   "ENABLE" "Enable an onion service" \
   "DISABLE" "Disable chosen onion service" \
